// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saveabkhpaemynlfcgcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhdmVhYmtocGFlbXlubGZjZ2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDg3MTEsImV4cCI6MjA2MDkyNDcxMX0.j_tE4-DSjls0uq1_LFd92Dpl3JwfrnGa1KlIhR9yzw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);